# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/buildSrc/"
    schedule:
      interval: "daily"
updates:
  - package-ecosystem: "gradle"
    directory: "/com.codaffine.tiny.demo/"
    schedule:
      interval: "daily"
updates:
  - package-ecosystem: "gradle"
    directory: "/com.codaffine.tiny.shared/"
    schedule:
      interval: "daily"
updates:
  - package-ecosystem: "gradle"
    directory: "/com.codaffine.tiny.star/"
    schedule:
      interval: "daily"
updates:
  - package-ecosystem: "gradle"
    directory: "/com.codaffine.tiny.star.cli/"
    schedule:
      interval: "daily"
updates:
  - package-ecosystem: "gradle"
    directory: "/com.codaffine.tiny.star.cli.basic/"
    schedule:
      interval: "daily"
updates:
  - package-ecosystem: "gradle"
    directory: "/com.codaffine.tiny.star.cli.tck/"
    schedule:
      interval: "daily"
updates:
  - package-ecosystem: "gradle"
    directory: "/com.codaffine.tiny.star.log4j/"
    schedule:
      interval: "daily"
updates:
  - package-ecosystem: "gradle"
    directory: "/com.codaffine.tiny.star.servlet/"
    schedule:
      interval: "daily"
updates:
  - package-ecosystem: "gradle"
    directory: "/com.codaffine.tiny.star.tck/"
    schedule:
      interval: "daily"
updates:
  - package-ecosystem: "gradle"
    directory: "/com.codaffine.tiny.star.tomcat/"
    schedule:
      interval: "daily"
updates:
  - package-ecosystem: "gradle"
    directory: "/com.codaffine.tiny.star.tomcat.bnd.dummy/"
    schedule:
      interval: "daily"
updates:
  - package-ecosystem: "gradle"
    directory: "/com.codaffine.tiny.star.tomcat.embed.core/"
    schedule:
      interval: "daily"
updates:
  - package-ecosystem: "gradle"
    directory: "/com.codaffine.tiny.star.tomcat.embed.el/"
    schedule:
      interval: "daily"
updates:
  - package-ecosystem: "gradle"
    directory: "/com.codaffine.tiny.star.tomcat.embed.jasper/"
    schedule:
      interval: "daily"
updates:
  - package-ecosystem: "gradle"
    directory: "/com.codaffine.tiny.star.undertow/"
    schedule:
      interval: "daily"
updates:
  - package-ecosystem: "gradle"
    directory: "/com.codaffine.tiny.test/"
    schedule:
      interval: "daily"
