name: Tiny Build
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew build
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/development'
    steps:
      - name: Generate JavaDoc
        run: ./gradlew :javadoc
      - name: Create Release
        run: ./gradlew :release -Prelease.dryRun
